### PR TITLE
Add support for varying sizes of inventories

### PR DESCRIPTION
**Pull request by BillyGalbreath**
This is especially handy for those servers that uses ender chests with other sizes than 3 rows, like mine. ;)

### CODE REVIEW

**Comment by Jikoo** [comment]
So for clarity, you have a plugin that actually modifies the EntityPlayer's ender chest? This seems like a good change regardless, the default container determination methods have several edge case issues with chest sizing as it is.

**Comment by BillyGalbreath** [comment]
> So for clarity, you have a plugin that actually modifies the EntityPlayer's ender chest?

I have a [fork of Paper](https://github.com/pl3xgaming/Purpur/blob/master/patches/server/0018-Add-large-sized-ender-chests.patch) that does it. ^_^

**Comment by Jikoo** [comment]
Very neatly done, much simpler than plugin-based expansion.

**Comment by RoboMWM** [comment]
I see you gave up on frienderchest which caused players on my server to lose items previously stored in the extra rows when it would fail to load on some startups xD

**Comment by BillyGalbreath** [comment]
> I see you gave up on frienderchest which caused players on my server to lose items previously stored in the extra rows when it would fail to load on some startups xD

Yeah, that plugin was a complete failure all the way around :3 lol

**Pull request merged**
